### ISSUE TITLE
What is the tissue for this chromatin state dataset?

### ISSUE THREAD

**Issue by unfashionable** [Arabidopsis-Information-Portal/chromatin_states_to_jbrowse#1]

**Comment by vivekkrish** [comment]
Hello @unfashionable,

This dataset was contributed to Araport by a community collaborator.

The information in their manuscript says: "ChIP analyses were performed using the aboveground tissues of 3-week-old seedlings."

Please refer to the **METHODS** section in the manuscript for detailed information: 
Joana Sequeira-Mendes, Irene Aragüez, Ramón Peiró, Raul Mendez-Giraldez, Xiaoyu Zhang, Steven E. Jacobsen, Ugo Bastolla, and Crisanto Gutierrez (2014) **The Functional Topography of the Arabidopsis Genome Is Organized in a Reduced Number of Linear Motifs of Chromatin States**. *Plant Cell*, doi:[10.1105/tpc.114.124578](http://www.plantcell.org/content/early/2014/06/11/tpc.114.124578)

Hope this information is useful to you!

Thank you.
Regards,
Vivek (on Behalf of Araport)

cc @agnespychan

**Comment by unfashionable** [comment]
Thank you. It helps a lot.
